name: bikeinsthlm
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^1.0.2
  flutter_sliding_up_panel: ^1.0.0
  flutter_screenutil: ^0.5.2
  expandable: ^4.1.3
  image_picker: ^0.6.6+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.25+3
  location: ^3.0.0
  geolocator: ^5.1.4+2
  flutter_mapbox_navigation: ^0.0.10
  http: ^0.12.0+4
  google_directions_api: ^0.5.0
  firebase_auth: ^0.16.0
  email_validator: ^1.0.4
  form_field_validator: ^1.0.1
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.5
  firebase_database: ^3.1.5
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.16
  intl: ^0.16.1
  basic_utils: ^1.5.0
  geocoder: ^0.2.1
  fluster: ^1.1.2
  google_maps_cluster_manager: ^0.1.0
  geohash: ^0.2.1
  charts_flutter: ^0.9.0
  great_circle_distance: ^1.0.1
  shared_preferences: ^0.5.7+2
  flutter_tts: ^1.2.0
  draggable_scrollbar: ^0.0.4
  fluttertoast: ^4.0.0
  oktoast: ^2.3.2
  flutter_spinkit: ^4.1.2
  firebase_messaging: ^6.0.16


 


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/newAppIcon.png"
  image_path_android: "assets/images/newAppIcon.png"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/files/
    - assets//images/
    - assets/images/logotype.png
    - assets/images/google.png
    - assets/images/roadDamage.png
    - assets/images/closedRoad.png
    - assets/images/obstacle.png
    - assets/images/heavyTraffic.png
    - assets/images/heavyTrafficPin.png
    - assets/images/otherDanger.png
    - assets/images/roadWork.png
    - assets/images/icyRoad.png
    - assets/images/roadSign.png
    - assets/images/pumpWorkingMarker.png
    - assets/images/pumpNotWorkingMarker.png
    - assets/images/warningPin.png
    - assets/images/roadWorkMarker.png
    - assets/images/heavyTrafficPin.png
    - assets/images/icyRoadPin.png
    - assets/images/obstaclePin.png
    - assets/images/otherDangerPin.png
    - assets/images/roadClosedPin.png
    - assets/images/roadDamagePin.png
    - assets/images/roadSignPin.png
    - assets/images/customRoadworkPin.png
    - assets/images/straightOn.png
    - assets/images/rightTurn.png
    - assets/images/leftTurn.png
    - assets/images/bearLeft.png
    - assets/images/bearRight.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

